# -*- coding: utf-8 -*-
"""LINE API services.

Two shapes live here, both taking the client as their only constructor
argument and reaching the network through ``client.request``:

* **Thrift RPC** -- ``talk``, ``square``, ``sync``, ``channel``, ``auth``.
  These subclass :class:`~linepy.services.base.ServiceBase`, which owns the
  endpoint, the protocol version, error translation and response-model
  validation. ``talk`` and ``sync`` are generated by
  ``tools/generate_models.py``; do not edit them by hand.
* **REST** -- ``timeline``, ``obs``, ``liff``, ``voom``. LINE serves these
  over plain HTTP with JSON or raw bodies, so they use the transport's
  ``get``/``post``/``http`` directly instead of ServiceBase.

Importing this package does not import the services: each one pulls in
:mod:`linepy.models.generated`, which :class:`~linepy.base.BaseClient`
defers until a client is actually constructed.
"""

from .base import ServiceBase

__all__ = ["ServiceBase"]
