# -*- coding: utf-8 -*-
# AUTO-GENERATED BY tools/generate_models.py
from __future__ import annotations
from typing import List, Optional, Dict, Any, Union
from pydantic import BaseModel, Field
from enum import IntEnum

class ApprovalValue(BaseModel):
    message: Optional[str] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class BooleanState(IntEnum):
    NONE = 0
    OFF = 1
    ON = 2

class ButtonContent(BaseModel):
    url_button: Optional["UrlButton"] = Field(alias="1", default=None)
    text_button: Optional["TextButton"] = Field(alias="2", default=None)
    ok_button: Optional["OkButton"] = Field(alias="3", default=None)

    class Config:
        populate_by_name = True

class CodeValue(BaseModel):
    code: Optional[str] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class CreateSquareChatThreadResponse(BaseModel):
    square_chat_thread: Optional["SquareChatThread"] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class CreateSquareResponse(BaseModel):
    square: Optional["Square"] = Field(alias="1", default=None)
    creator: Optional["SquareMember"] = Field(alias="2", default=None)
    authority: Optional["SquareAuthority"] = Field(alias="3", default=None)
    status: Optional["SquareStatus"] = Field(alias="4", default=None)
    feature_set: Optional["SquareFeatureSet"] = Field(alias="5", default=None)
    note_status: Optional["NoteStatus"] = Field(alias="6", default=None)
    square_chat: Optional["SquareChat"] = Field(alias="7", default=None)
    square_chat_status: Optional["SquareChatStatus"] = Field(alias="8", default=None)
    square_chat_member: Optional["SquareChatMember"] = Field(alias="9", default=None)
    square_chat_feature_set: Optional["SquareChatFeatureSet"] = Field(alias="10", default=None)

    class Config:
        populate_by_name = True

class FetchMyEventsResponse(BaseModel):
    subscription: Optional["SubscriptionState"] = Field(alias="1", default=None)
    events: List["SquareEvent"] = Field(alias="2", default_factory=list)
    sync_token: Optional[str] = Field(alias="3", default=None)
    continuation_token: Optional[str] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class FetchSquareChatEventsResponse(BaseModel):
    subscription: Optional["SubscriptionState"] = Field(alias="1", default=None)
    events: List["SquareEvent"] = Field(alias="2", default_factory=list)
    sync_token: Optional[str] = Field(alias="3", default=None)
    continuation_token: Optional[str] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class FindSquareByInvitationTicketResponse(BaseModel):
    square: Optional["Square"] = Field(alias="1", default=None)
    my_membership: Optional["SquareMember"] = Field(alias="2", default=None)
    square_authority: Optional["SquareAuthority"] = Field(alias="3", default=None)
    square_status: Optional["SquareStatus"] = Field(alias="4", default=None)
    square_feature_set: Optional["SquareFeatureSet"] = Field(alias="5", default=None)
    note_status: Optional["NoteStatus"] = Field(alias="6", default=None)
    chat: Optional["SquareChat"] = Field(alias="7", default=None)
    chat_status: Optional["SquareChatStatus"] = Field(alias="8", default=None)

    class Config:
        populate_by_name = True

class GetJoinableSquareChatsResponse(BaseModel):
    square_chats: List["SquareChat"] = Field(alias="1", default_factory=list)
    continuation_token: Optional[str] = Field(alias="2", default=None)
    total_square_chat_count: int = Field(alias="3", default=0)
    square_chat_statuses: Dict[str, "SquareChatStatus"] = Field(alias="4", default_factory=dict)

    class Config:
        populate_by_name = True

class GetJoinedSquareChatThreadsResponse(BaseModel):
    square_chat_threads: List["SquareChatThread"] = Field(alias="1", default_factory=list)
    continuation_token: Optional[str] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class GetJoinedSquaresResponse(BaseModel):
    squares: List["Square"] = Field(alias="1", default_factory=list)
    members: Dict[str, "SquareMember"] = Field(alias="2", default_factory=dict)
    authorities: Dict[str, "SquareAuthority"] = Field(alias="3", default_factory=dict)
    statuses: Dict[str, "SquareStatus"] = Field(alias="4", default_factory=dict)
    continuation_token: Optional[str] = Field(alias="5", default=None)
    note_statuses: Dict[str, "NoteStatus"] = Field(alias="6", default_factory=dict)

    class Config:
        populate_by_name = True

class GetSquareChatAnnouncementsResponse(BaseModel):
    announcements: List["SquareChatAnnouncement"] = Field(alias="1", default_factory=list)

    class Config:
        populate_by_name = True

class GetSquareChatFeatureSetResponse(BaseModel):
    square_chat_feature_set: Optional["SquareChatFeatureSet"] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class GetSquareChatThreadResponse(BaseModel):
    square_chat_thread: Optional["SquareChatThread"] = Field(alias="1", default=None)
    my_square_chat_thread_member: Optional["SquareChatThreadMember"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class GetSquareEmidResponse(BaseModel):
    square_emid: Optional[str] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class GetSquareFeatureSetResponse(BaseModel):
    square_feature_set: Optional["SquareFeatureSet"] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class GetSquareMembersBySquareResponse(BaseModel):
    members: List["SquareMember"] = Field(alias="1", default_factory=list)

    class Config:
        populate_by_name = True

class GetSquareResponse(BaseModel):
    square: Optional["Square"] = Field(alias="1", default=None)
    my_membership: Optional["SquareMember"] = Field(alias="2", default=None)
    square_authority: Optional["SquareAuthority"] = Field(alias="3", default=None)
    square_status: Optional["SquareStatus"] = Field(alias="4", default=None)
    square_feature_set: Optional["SquareFeatureSet"] = Field(alias="5", default=None)
    note_status: Optional["NoteStatus"] = Field(alias="6", default=None)

    class Config:
        populate_by_name = True

class InviteIntoSquareChatResponse(BaseModel):
    invitee_mids: List[str] = Field(alias="1", default_factory=list)

    class Config:
        populate_by_name = True

class InviteToSquareResponse(BaseModel):
    pass

    class Config:
        populate_by_name = True

class JoinSquareChatThreadResponse(BaseModel):
    square_chat_thread: Optional["SquareChatThread"] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class ManualRepairResponse(BaseModel):
    events: List["SquareEvent"] = Field(alias="1", default_factory=list)
    sync_token: Optional[str] = Field(alias="2", default=None)
    continuation_token: Optional[str] = Field(alias="3", default=None)

    class Config:
        populate_by_name = True

class MarkAsReadResponse(BaseModel):
    pass

    class Config:
        populate_by_name = True

class MessageStatusContents(BaseModel):
    message_reaction_status: Optional["SquareMessageReactionStatus"] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class MessageStatusType(IntEnum):
    MESSAGE_REACTION = 0

class MessageVisibility(BaseModel):
    show_join_message: bool = Field(alias="1", default=False)
    show_leave_message: bool = Field(alias="2", default=False)
    show_kickout_message: bool = Field(alias="3", default=False)

    class Config:
        populate_by_name = True

class NoteStatus(BaseModel):
    note_count: int = Field(alias="1", default=0)
    latest_created_at: int = Field(alias="2", default=0)

    class Config:
        populate_by_name = True

class NotificationPostType(IntEnum):
    POST_MENTION = 2
    POST_LIKE = 3
    POST_COMMENT = 4
    POST_COMMENT_MENTION = 5
    POST_COMMENT_LIKE = 6
    POST_RELAY_JOIN = 7

class NotifiedMessageType(IntEnum):
    MENTION = 1
    REPLY = 2

class OkButton(BaseModel):
    text: Optional[str] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class ReactToMessageResponse(BaseModel):
    reaction: Optional["SquareMessageReaction"] = Field(alias="1", default=None)
    status: Optional["SquareMessageReactionStatus"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SendMessageResponse(BaseModel):
    created_square_message: Optional["SquareMessage"] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class SneakPeekContent(BaseModel):
    title: Optional[str] = Field(alias="1", default=None)
    desc: Optional[str] = Field(alias="2", default=None)
    image_obs_hashes: List[str] = Field(alias="3", default_factory=list)

    class Config:
        populate_by_name = True

class Square(BaseModel):
    mid: Optional[str] = Field(alias="1", default=None)
    name: Optional[str] = Field(alias="2", default=None)
    welcome_message: Optional[str] = Field(alias="3", default=None)
    profile_image_obs_hash: Optional[str] = Field(alias="4", default=None)
    desc: Optional[str] = Field(alias="5", default=None)
    searchable: bool = Field(alias="6", default=False)
    type_: Optional["SquareType"] = Field(alias="7", default=None)
    category_id: int = Field(alias="8", default=0)
    invitation_url: Optional[str] = Field(alias="9", default=None)
    revision: int = Field(alias="10", default=0)
    able_to_use_invitation_ticket: bool = Field(alias="11", default=False)
    state: Optional["SquareState"] = Field(alias="12", default=None)
    emblems: List["SquareEmblem"] = Field(alias="13", default_factory=list)
    join_method: Optional["SquareJoinMethod"] = Field(alias="14", default=None)
    adult_only: Optional["BooleanState"] = Field(alias="15", default=None)
    svc_tags: List[str] = Field(alias="16", default_factory=list)
    created_at: int = Field(alias="17", default=0)
    paid_square: bool = Field(alias="18", default=False)
    benefit_keywords: List[str] = Field(alias="19", default_factory=list)
    sneak_peek_contents: List["SneakPeekContent"] = Field(alias="20", default_factory=list)
    expire_at: int = Field(alias="21", default=0)

    class Config:
        populate_by_name = True

class SquareAuthority(BaseModel):
    square_mid: Optional[str] = Field(alias="1", default=None)
    update_square_profile: Optional["SquareMemberRole"] = Field(alias="2", default=None)
    invite_new_member: Optional["SquareMemberRole"] = Field(alias="3", default=None)
    approve_join_request: Optional["SquareMemberRole"] = Field(alias="4", default=None)
    create_post: Optional["SquareMemberRole"] = Field(alias="5", default=None)
    create_open_square_chat: Optional["SquareMemberRole"] = Field(alias="6", default=None)
    delete_square_chat_or_post: Optional["SquareMemberRole"] = Field(alias="7", default=None)
    remove_square_member: Optional["SquareMemberRole"] = Field(alias="8", default=None)
    grant_role: Optional["SquareMemberRole"] = Field(alias="9", default=None)
    enable_invitation_ticket: Optional["SquareMemberRole"] = Field(alias="10", default=None)
    revision: int = Field(alias="11", default=0)
    create_square_chat_announcement: Optional["SquareMemberRole"] = Field(alias="12", default=None)
    update_max_chat_member_count: Optional["SquareMemberRole"] = Field(alias="13", default=None)
    use_readonly_default_chat: Optional["SquareMemberRole"] = Field(alias="14", default=None)
    send_all_mention: Optional["SquareMemberRole"] = Field(alias="15", default=None)

    class Config:
        populate_by_name = True

class SquareChat(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square_mid: Optional[str] = Field(alias="2", default=None)
    type_: Optional["SquareChatType"] = Field(alias="3", default=None)
    name: Optional[str] = Field(alias="4", default=None)
    chat_image_obs_hash: Optional[str] = Field(alias="5", default=None)
    square_chat_revision: int = Field(alias="6", default=0)
    max_member_count: int = Field(alias="7", default=0)
    state: Optional["SquareChatState"] = Field(alias="8", default=None)
    invitation_url: Optional[str] = Field(alias="9", default=None)
    message_visibility: Optional["MessageVisibility"] = Field(alias="10", default=None)
    able_to_search_message: Optional["BooleanState"] = Field(alias="11", default=None)

    class Config:
        populate_by_name = True

class SquareChatAnnouncement(BaseModel):
    announcement_seq: int = Field(alias="1", default=0)
    type_: Optional[Any] = Field(alias="2", default=None)
    contents: Optional["SquareChatAnnouncementContents"] = Field(alias="3", default=None)
    created_at: int = Field(alias="4", default=0)
    creator: Optional[str] = Field(alias="5", default=None)

    class Config:
        populate_by_name = True

class SquareChatAnnouncementContents(BaseModel):
    text_message_announcement_contents: Optional["TextMessageAnnouncementContents"] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class SquareChatFeature(BaseModel):
    control_state: Optional["SquareChatFeatureControlState"] = Field(alias="1", default=None)
    boolean_value: Optional["BooleanState"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareChatFeatureControlState(IntEnum):
    DISABLED = 1
    ENABLED = 2

class SquareChatFeatureSet(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    revision: int = Field(alias="2", default=0)
    disable_update_max_chat_member_count: Optional["SquareChatFeature"] = Field(alias="11", default=None)
    disable_mark_as_read_event: Optional["SquareChatFeature"] = Field(alias="12", default=None)

    class Config:
        populate_by_name = True

class SquareChatMember(BaseModel):
    square_member_mid: Optional[str] = Field(alias="1", default=None)
    square_chat_mid: Optional[str] = Field(alias="2", default=None)
    revision: int = Field(alias="3", default=0)
    membership_state: Optional["SquareChatMembershipState"] = Field(alias="4", default=None)
    notification_for_message: bool = Field(alias="5", default=False)
    notification_for_new_member: bool = Field(alias="6", default=False)

    class Config:
        populate_by_name = True

class SquareChatMembershipState(IntEnum):
    JOINED = 1
    LEFT = 2

class SquareChatState(IntEnum):
    ALIVE = 0
    DELETED = 1
    SUSPENDED = 2

class SquareChatStatus(BaseModel):
    last_message: Optional["SquareMessage"] = Field(alias="3", default=None)
    sender_display_name: Optional[str] = Field(alias="4", default=None)
    other_status: Optional["SquareChatStatusWithoutMessage"] = Field(alias="5", default=None)

    class Config:
        populate_by_name = True

class SquareChatStatusWithoutMessage(BaseModel):
    member_count: int = Field(alias="1", default=0)
    unread_message_count: int = Field(alias="2", default=0)
    marked_as_read_message_id: Optional[str] = Field(alias="3", default=None)
    mentioned_message_id: Optional[str] = Field(alias="4", default=None)
    notified_message_type: Optional["NotifiedMessageType"] = Field(alias="5", default=None)
    badges: List["StatusBadge"] = Field(alias="6", default_factory=list)

    class Config:
        populate_by_name = True

class SquareChatThread(BaseModel):
    square_chat_thread_mid: Optional[str] = Field(alias="1", default=None)
    square_chat_mid: Optional[str] = Field(alias="2", default=None)
    square_mid: Optional[str] = Field(alias="3", default=None)
    message_id: Optional[str] = Field(alias="4", default=None)
    state: Optional["SquareChatThreadState"] = Field(alias="5", default=None)

    class Config:
        populate_by_name = True

class SquareChatThreadMember(BaseModel):
    square_member_mid: Optional[str] = Field(alias="1", default=None)
    square_chat_thread_mid: Optional[str] = Field(alias="2", default=None)
    revision: int = Field(alias="3", default=0)
    membership_state: Optional["SquareChatThreadeMembershipState"] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareChatThreadState(IntEnum):
    ACTIVE = 1
    INACTIVE = 2

class SquareChatThreadeMembershipState(IntEnum):
    ACTIVATED = 1
    DEACTIVATED = 2

class SquareChatType(IntEnum):
    OPEN = 1
    SECRET = 2
    ONE_ON_ONE = 3
    SQUARE_DEFAULT = 4

class SquareEmblem(IntEnum):
    SUPER = 1
    OFFICIAL = 2

class SquareEvent(BaseModel):
    created_time: int = Field(alias="2", default=0)
    type_: Optional["SquareEventType"] = Field(alias="3", default=None)
    payload: Optional["SquareEventPayload"] = Field(alias="4", default=None)
    sync_token: Optional[str] = Field(alias="5", default=None)
    event_status: Optional["SquareEventStatus"] = Field(alias="6", default=None)

    class Config:
        populate_by_name = True

class SquareEventChatPopup(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    popup_id: int = Field(alias="2", default=0)
    flex_json: Optional[str] = Field(alias="3", default=None)
    button: Optional["ButtonContent"] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareEventMutateMessage(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square_message: Optional["SquareMessage"] = Field(alias="2", default=None)
    req_seq: int = Field(alias="3", default=0)
    sender_display_name: Optional[str] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotificationJoinRequest(BaseModel):
    square_mid: Optional[str] = Field(alias="1", default=None)
    square_name: Optional[str] = Field(alias="2", default=None)
    request_member_name: Optional[str] = Field(alias="3", default=None)
    profile_image_obs_hash: Optional[str] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotificationLiveTalk(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    live_talk_invitation_ticket: Optional[str] = Field(alias="2", default=None)
    square_chat_name: Optional[str] = Field(alias="3", default=None)
    chat_image_obs_hash: Optional[str] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotificationMemberUpdate(BaseModel):
    square_mid: Optional[str] = Field(alias="1", default=None)
    square_name: Optional[str] = Field(alias="2", default=None)
    profile_image_obs_hash: Optional[str] = Field(alias="3", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotificationMessage(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square_message: Optional["SquareMessage"] = Field(alias="2", default=None)
    sender_display_name: Optional[str] = Field(alias="3", default=None)
    unread_count: int = Field(alias="4", default=0)
    required_to_fetch_chat_events: bool = Field(alias="5", default=False)
    mentioned_message_id: Optional[str] = Field(alias="6", default=None)
    notified_message_type: Optional["NotifiedMessageType"] = Field(alias="7", default=None)
    req_seq: int = Field(alias="8", default=0)

    class Config:
        populate_by_name = True

class SquareEventNotificationMessageReaction(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    message_id: Optional[str] = Field(alias="2", default=None)
    square_chat_name: Optional[str] = Field(alias="3", default=None)
    reactor_name: Optional[str] = Field(alias="4", default=None)
    thumbnail_obs_hash: Optional[str] = Field(alias="5", default=None)
    message_text: Optional[str] = Field(alias="6", default=None)
    type_: Optional[Any] = Field(alias="7", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotificationNewChatMember(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square_chat_name: Optional[str] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotificationPost(BaseModel):
    square_mid: Optional[str] = Field(alias="1", default=None)
    notification_post_type: Optional["NotificationPostType"] = Field(alias="2", default=None)
    thumbnail_obs_hash: Optional[str] = Field(alias="3", default=None)
    text: Optional[str] = Field(alias="4", default=None)
    action_uri: Optional[str] = Field(alias="5", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotificationPostAnnouncement(BaseModel):
    square_mid: Optional[str] = Field(alias="1", default=None)
    square_name: Optional[str] = Field(alias="2", default=None)
    square_profile_image_obs_hash: Optional[str] = Field(alias="3", default=None)
    action_uri: Optional[str] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotificationSquareChatDelete(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square_chat_name: Optional[str] = Field(alias="2", default=None)
    profile_image_obs_hash: Optional[str] = Field(alias="3", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotificationSquareDelete(BaseModel):
    square_mid: Optional[str] = Field(alias="1", default=None)
    square_name: Optional[str] = Field(alias="2", default=None)
    profile_image_obs_hash: Optional[str] = Field(alias="3", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotificationThreadMessage(BaseModel):
    thread_mid: Optional[str] = Field(alias="1", default=None)
    chat_mid: Optional[str] = Field(alias="2", default=None)
    square_message: Optional["SquareMessage"] = Field(alias="3", default=None)
    sender_display_name: Optional[str] = Field(alias="4", default=None)
    unread_count: int = Field(alias="5", default=0)
    total_message_count: int = Field(alias="6", default=0)
    thread_root_message_id: Optional[str] = Field(alias="7", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotificationThreadMessageReaction(BaseModel):
    thread_mid: Optional[str] = Field(alias="1", default=None)
    chat_mid: Optional[str] = Field(alias="2", default=None)
    message_id: Optional[str] = Field(alias="3", default=None)
    sender_display_name: Optional[str] = Field(alias="4", default=None)
    square_chat_name: Optional[str] = Field(alias="5", default=None)
    reactor_name: Optional[str] = Field(alias="6", default=None)
    thumbnail_obs_hash: Optional[str] = Field(alias="7", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedAddBot(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square_member: Optional["SquareMember"] = Field(alias="2", default=None)
    bot_mid: Optional[str] = Field(alias="3", default=None)
    bot_display_name: Optional[str] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedCreateSquareChatMember(BaseModel):
    chat: Optional["SquareChat"] = Field(alias="1", default=None)
    chat_status: Optional["SquareChatStatus"] = Field(alias="2", default=None)
    chat_member: Optional["SquareChatMember"] = Field(alias="3", default=None)
    joined_at: int = Field(alias="4", default=0)
    peer_square_member: Optional["SquareMember"] = Field(alias="5", default=None)
    square_chat_feature_set: Optional["SquareChatFeatureSet"] = Field(alias="6", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedCreateSquareMember(BaseModel):
    square: Optional["Square"] = Field(alias="1", default=None)
    square_authority: Optional["SquareAuthority"] = Field(alias="2", default=None)
    square_status: Optional["SquareStatus"] = Field(alias="3", default=None)
    square_member: Optional["SquareMember"] = Field(alias="4", default=None)
    square_feature_set: Optional["SquareFeatureSet"] = Field(alias="5", default=None)
    note_status: Optional["NoteStatus"] = Field(alias="6", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedDeleteSquareChat(BaseModel):
    square_chat: Optional["SquareChat"] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedDestroyMessage(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    message_id: Optional[str] = Field(alias="3", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedInviteIntoSquareChat(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    invitees: List["SquareMember"] = Field(alias="2", default_factory=list)
    invitor: Optional["SquareMember"] = Field(alias="3", default=None)
    invitor_relation: Optional["SquareMemberRelation"] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedJoinSquareChat(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    joined_member: Optional["SquareMember"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedKickoutFromSquare(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    kickees: List["SquareMember"] = Field(alias="2", default_factory=list)
    kicker: Optional["SquareMember"] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedLeaveSquareChat(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square_member_mid: Optional[str] = Field(alias="2", default=None)
    say_goodbye: bool = Field(alias="3", default=False)
    square_member: Optional["SquareMember"] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedMarkAsRead(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    s_member_mid: Optional[str] = Field(alias="2", default=None)
    message_id: Optional[str] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedRemoveBot(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square_member: Optional["SquareMember"] = Field(alias="2", default=None)
    bot_mid: Optional[str] = Field(alias="3", default=None)
    bot_display_name: Optional[str] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedShutdownSquare(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square: Optional["Square"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedSystemMessage(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    text: Optional[str] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateLiveTalk(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    session_id: Optional[str] = Field(alias="2", default=None)
    live_talk_on_air: bool = Field(alias="3", default=False)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateLiveTalkInfo(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    live_talk: Optional[Any] = Field(alias="2", default=None)
    live_talk_on_air: bool = Field(alias="3", default=False)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateMessageStatus(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    message_id: Optional[str] = Field(alias="2", default=None)
    message_status: Optional["SquareMessageStatus"] = Field(alias="3", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateReadonlyChat(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    readonly: bool = Field(alias="2", default=False)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquare(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square: Optional["Square"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareAuthority(BaseModel):
    square_mid: Optional[str] = Field(alias="1", default=None)
    square_authority: Optional["SquareAuthority"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareChat(BaseModel):
    square_mid: Optional[str] = Field(alias="1", default=None)
    square_chat_mid: Optional[str] = Field(alias="2", default=None)
    square_chat: Optional["SquareChat"] = Field(alias="3", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareChatAnnouncement(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    announcement_seq: int = Field(alias="2", default=0)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareChatFeatureSet(BaseModel):
    square_chat_feature_set: Optional["SquareChatFeatureSet"] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareChatMaxMemberCount(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    max_member_count: int = Field(alias="2", default=0)
    editor: Optional["SquareMember"] = Field(alias="3", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareChatMember(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    arg__square_chat_member: Optional["SquareChatMember"] = Field(alias="2", default=None)
    square_chat_member: Optional["SquareChatMember"] = Field(alias="3", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareChatProfileImage(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    editor: Optional["SquareMember"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareChatProfileName(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    editor: Optional["SquareMember"] = Field(alias="2", default=None)
    updated_chat_name: Optional[str] = Field(alias="3", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareChatStatus(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    status_without_message: Optional["SquareChatStatusWithoutMessage"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareFeatureSet(BaseModel):
    square_feature_set: Optional["SquareFeatureSet"] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareMember(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square_member_mid: Optional[str] = Field(alias="2", default=None)
    square_member: Optional["SquareMember"] = Field(alias="3", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareMemberProfile(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square_member: Optional["SquareMember"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareMemberRelation(BaseModel):
    square_mid: Optional[str] = Field(alias="1", default=None)
    my_member_mid: Optional[str] = Field(alias="2", default=None)
    target_square_member_mid: Optional[str] = Field(alias="3", default=None)
    square_member_relation: Optional["SquareMemberRelation"] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareNoteStatus(BaseModel):
    square_mid: Optional[str] = Field(alias="1", default=None)
    note_status: Optional["NoteStatus"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateSquareStatus(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square_status: Optional["SquareStatus"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateThread(BaseModel):
    square_thread: Optional["SquareThread"] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateThreadMember(BaseModel):
    thread_member: Optional["SquareThreadMember"] = Field(alias="1", default=None)
    square_thread: Optional["SquareThread"] = Field(alias="2", default=None)
    thread_root_message: Optional["SquareMessage"] = Field(alias="3", default=None)
    total_message_count: int = Field(alias="4", default=0)
    last_message: Optional["SquareMessage"] = Field(alias="5", default=None)
    last_message_sender_display_name: Optional[str] = Field(alias="6", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateThreadRootMessage(BaseModel):
    square_thread: Optional["SquareThread"] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateThreadRootMessageStatus(BaseModel):
    chat_mid: Optional[str] = Field(alias="1", default=None)
    thread_mid: Optional[str] = Field(alias="2", default=None)
    thread_root_message_id: Optional[str] = Field(alias="3", default=None)
    total_message_count: int = Field(alias="4", default=0)
    last_message_at: int = Field(alias="5", default=0)

    class Config:
        populate_by_name = True

class SquareEventNotifiedUpdateThreadStatus(BaseModel):
    thread_mid: Optional[str] = Field(alias="1", default=None)
    chat_mid: Optional[str] = Field(alias="2", default=None)
    unread_count: int = Field(alias="3", default=0)
    mark_as_read_message_id: Optional[str] = Field(alias="4", default=None)

    class Config:
        populate_by_name = True

class SquareEventPayload(BaseModel):
    receive_message: Optional["SquareEventReceiveMessage"] = Field(alias="1", default=None)
    send_message: Optional["SquareEventSendMessage"] = Field(alias="2", default=None)
    notified_join_square_chat: Optional["SquareEventNotifiedJoinSquareChat"] = Field(alias="3", default=None)
    notified_invite_into_square_chat: Optional["SquareEventNotifiedInviteIntoSquareChat"] = Field(alias="4", default=None)
    notified_leave_square_chat: Optional["SquareEventNotifiedLeaveSquareChat"] = Field(alias="5", default=None)
    notified_destroy_message: Optional["SquareEventNotifiedDestroyMessage"] = Field(alias="6", default=None)
    notified_mark_as_read: Optional["SquareEventNotifiedMarkAsRead"] = Field(alias="7", default=None)
    notified_update_square_member_profile: Optional["SquareEventNotifiedUpdateSquareMemberProfile"] = Field(alias="8", default=None)
    notified_update_square: Optional["SquareEventNotifiedUpdateSquare"] = Field(alias="9", default=None)
    notified_update_square_member: Optional["SquareEventNotifiedUpdateSquareMember"] = Field(alias="10", default=None)
    notified_update_square_chat: Optional["SquareEventNotifiedUpdateSquareChat"] = Field(alias="11", default=None)
    notified_update_square_chat_member: Optional["SquareEventNotifiedUpdateSquareChatMember"] = Field(alias="12", default=None)
    notified_update_square_authority: Optional["SquareEventNotifiedUpdateSquareAuthority"] = Field(alias="13", default=None)
    notified_update_square_status: Optional["SquareEventNotifiedUpdateSquareStatus"] = Field(alias="14", default=None)
    notified_update_square_chat_status: Optional["SquareEventNotifiedUpdateSquareChatStatus"] = Field(alias="15", default=None)
    notified_create_square_member: Optional["SquareEventNotifiedCreateSquareMember"] = Field(alias="16", default=None)
    notified_create_square_chat_member: Optional["SquareEventNotifiedCreateSquareChatMember"] = Field(alias="17", default=None)
    notified_update_square_member_relation: Optional["SquareEventNotifiedUpdateSquareMemberRelation"] = Field(alias="18", default=None)
    notified_shutdown_square: Optional["SquareEventNotifiedShutdownSquare"] = Field(alias="19", default=None)
    notified_kickout_from_square: Optional["SquareEventNotifiedKickoutFromSquare"] = Field(alias="20", default=None)
    notified_delete_square_chat: Optional["SquareEventNotifiedDeleteSquareChat"] = Field(alias="21", default=None)
    notification_join_request: Optional["SquareEventNotificationJoinRequest"] = Field(alias="22", default=None)
    notification_joined: Optional["SquareEventNotificationMemberUpdate"] = Field(alias="23", default=None)
    notification_promote_coadmin: Optional["SquareEventNotificationMemberUpdate"] = Field(alias="24", default=None)
    notification_promote_admin: Optional["SquareEventNotificationMemberUpdate"] = Field(alias="25", default=None)
    notification_demote_member: Optional["SquareEventNotificationMemberUpdate"] = Field(alias="26", default=None)
    notification_kicked_out: Optional["SquareEventNotificationMemberUpdate"] = Field(alias="27", default=None)
    notification_square_delete: Optional["SquareEventNotificationSquareDelete"] = Field(alias="28", default=None)
    notification_square_chat_delete: Optional["SquareEventNotificationSquareChatDelete"] = Field(alias="29", default=None)
    notification_message: Optional["SquareEventNotificationMessage"] = Field(alias="30", default=None)
    notified_update_square_chat_profile_name: Optional["SquareEventNotifiedUpdateSquareChatProfileName"] = Field(alias="31", default=None)
    notified_update_square_chat_profile_image: Optional["SquareEventNotifiedUpdateSquareChatProfileImage"] = Field(alias="32", default=None)
    notified_update_square_feature_set: Optional["SquareEventNotifiedUpdateSquareFeatureSet"] = Field(alias="33", default=None)
    notified_add_bot: Optional["SquareEventNotifiedAddBot"] = Field(alias="34", default=None)
    notified_remove_bot: Optional["SquareEventNotifiedRemoveBot"] = Field(alias="35", default=None)
    notified_update_square_note_status: Optional["SquareEventNotifiedUpdateSquareNoteStatus"] = Field(alias="36", default=None)
    notified_update_square_chat_announcement: Optional["SquareEventNotifiedUpdateSquareChatAnnouncement"] = Field(alias="37", default=None)
    notified_update_square_chat_max_member_count: Optional["SquareEventNotifiedUpdateSquareChatMaxMemberCount"] = Field(alias="38", default=None)
    notification_post_announcement: Optional["SquareEventNotificationPostAnnouncement"] = Field(alias="39", default=None)
    notification_post: Optional["SquareEventNotificationPost"] = Field(alias="40", default=None)
    mutate_message: Optional["SquareEventMutateMessage"] = Field(alias="41", default=None)
    notification_new_chat_member: Optional["SquareEventNotificationNewChatMember"] = Field(alias="42", default=None)
    notified_update_readonly_chat: Optional["SquareEventNotifiedUpdateReadonlyChat"] = Field(alias="43", default=None)
    notified_update_message_status: Optional["SquareEventNotifiedUpdateMessageStatus"] = Field(alias="44", default=None)
    notification_message_reaction: Optional["SquareEventNotificationMessageReaction"] = Field(alias="45", default=None)
    chat_popup: Optional["SquareEventChatPopup"] = Field(alias="46", default=None)
    notified_system_message: Optional["SquareEventNotifiedSystemMessage"] = Field(alias="47", default=None)
    notified_update_square_chat_feature_set: Optional["SquareEventNotifiedUpdateSquareChatFeatureSet"] = Field(alias="48", default=None)
    notified_update_live_talk_info: Optional["SquareEventNotifiedUpdateLiveTalkInfo"] = Field(alias="49", default=None)
    notified_update_live_talk: Optional["SquareEventNotifiedUpdateLiveTalk"] = Field(alias="50", default=None)
    notification_live_talk: Optional["SquareEventNotificationLiveTalk"] = Field(alias="51", default=None)
    notification_thread_message: Optional["SquareEventNotificationThreadMessage"] = Field(alias="52", default=None)
    notification_thread_message_reaction: Optional["SquareEventNotificationThreadMessageReaction"] = Field(alias="53", default=None)
    notified_update_thread: Optional["SquareEventNotifiedUpdateThread"] = Field(alias="54", default=None)
    notified_update_thread_status: Optional["SquareEventNotifiedUpdateThreadStatus"] = Field(alias="55", default=None)
    notified_update_thread_member: Optional["SquareEventNotifiedUpdateThreadMember"] = Field(alias="56", default=None)
    notified_update_thread_root_message: Optional["SquareEventNotifiedUpdateThreadRootMessage"] = Field(alias="57", default=None)
    notified_update_thread_root_message_status: Optional["SquareEventNotifiedUpdateThreadRootMessageStatus"] = Field(alias="58", default=None)

    class Config:
        populate_by_name = True

class SquareEventReceiveMessage(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square_message: Optional["SquareMessage"] = Field(alias="2", default=None)
    sender_display_name: Optional[str] = Field(alias="3", default=None)
    message_reaction_status: Optional["SquareMessageReactionStatus"] = Field(alias="4", default=None)
    sender_revision: int = Field(alias="5", default=0)
    square_mid: Optional[str] = Field(alias="6", default=None)

    class Config:
        populate_by_name = True

class SquareEventSendMessage(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    square_message: Optional["SquareMessage"] = Field(alias="2", default=None)
    req_seq: int = Field(alias="3", default=0)
    sender_display_name: Optional[str] = Field(alias="4", default=None)
    message_reaction_status: Optional["SquareMessageReactionStatus"] = Field(alias="5", default=None)

    class Config:
        populate_by_name = True

class SquareEventStatus(IntEnum):
    NORMAL = 1
    ALERT_DISABLED = 2

class SquareEventType(IntEnum):
    RECEIVE_MESSAGE = 0
    SEND_MESSAGE = 1
    NOTIFIED_JOIN_SQUARE_CHAT = 2
    NOTIFIED_INVITE_INTO_SQUARE_CHAT = 3
    NOTIFIED_LEAVE_SQUARE_CHAT = 4
    NOTIFIED_DESTROY_MESSAGE = 5
    NOTIFIED_MARK_AS_READ = 6
    NOTIFIED_UPDATE_SQUARE_MEMBER_PROFILE = 7
    NOTIFIED_UPDATE_SQUARE = 8
    NOTIFIED_UPDATE_SQUARE_STATUS = 9
    NOTIFIED_UPDATE_SQUARE_AUTHORITY = 10
    NOTIFIED_UPDATE_SQUARE_MEMBER = 11
    NOTIFIED_UPDATE_SQUARE_CHAT = 12
    NOTIFIED_UPDATE_SQUARE_CHAT_STATUS = 13
    NOTIFIED_UPDATE_SQUARE_CHAT_MEMBER = 14
    NOTIFIED_CREATE_SQUARE_MEMBER = 15
    NOTIFIED_CREATE_SQUARE_CHAT_MEMBER = 16
    NOTIFIED_UPDATE_SQUARE_MEMBER_RELATION = 17
    NOTIFIED_SHUTDOWN_SQUARE = 18
    NOTIFIED_KICKOUT_FROM_SQUARE = 19
    NOTIFIED_DELETE_SQUARE_CHAT = 20
    NOTIFICATION_JOIN_REQUEST = 21
    NOTIFICATION_JOINED = 22
    NOTIFICATION_PROMOTED_COADMIN = 23
    NOTIFICATION_PROMOTED_ADMIN = 24
    NOTIFICATION_DEMOTED_MEMBER = 25
    NOTIFICATION_KICKED_OUT = 26
    NOTIFICATION_SQUARE_DELETE = 27
    NOTIFICATION_SQUARE_CHAT_DELETE = 28
    NOTIFICATION_MESSAGE = 29
    NOTIFIED_UPDATE_SQUARE_CHAT_PROFILE_NAME = 30
    NOTIFIED_UPDATE_SQUARE_CHAT_PROFILE_IMAGE = 31
    NOTIFIED_UPDATE_SQUARE_FEATURE_SET = 32
    NOTIFIED_ADD_BOT = 33
    NOTIFIED_REMOVE_BOT = 34
    NOTIFIED_UPDATE_SQUARE_NOTE_STATUS = 36
    NOTIFIED_UPDATE_SQUARE_CHAT_ANNOUNCEMENT = 37
    NOTIFIED_UPDATE_SQUARE_CHAT_MAX_MEMBER_COUNT = 38
    NOTIFICATION_POST_ANNOUNCEMENT = 39
    NOTIFICATION_POST = 40
    MUTATE_MESSAGE = 41
    NOTIFICATION_NEW_CHAT_MEMBER = 42
    NOTIFIED_UPDATE_READONLY_CHAT = 43
    NOTIFIED_UPDATE_MESSAGE_STATUS = 46
    NOTIFICATION_MESSAGE_REACTION = 47
    NOTIFIED_CHAT_POPUP = 48
    NOTIFIED_SYSTEM_MESSAGE = 49
    NOTIFIED_UPDATE_SQUARE_CHAT_FEATURE_SET = 50
    NOTIFIED_UPDATE_LIVE_TALK = 51
    NOTIFICATION_LIVE_TALK = 52
    NOTIFIED_UPDATE_LIVE_TALK_INFO = 53
    NOTIFICATION_THREAD_MESSAGE = 54
    NOTIFICATION_THREAD_MESSAGE_REACTION = 55
    NOTIFIED_UPDATE_THREAD = 56
    NOTIFIED_UPDATE_THREAD_STATUS = 57
    NOTIFIED_UPDATE_THREAD_MEMBER = 58
    NOTIFIED_UPDATE_THREAD_ROOT_MESSAGE = 59
    NOTIFIED_UPDATE_THREAD_ROOT_MESSAGE_STATUS = 60

class SquareFeature(BaseModel):
    control_state: Optional["SquareFeatureControlState"] = Field(alias="1", default=None)
    boolean_value: Optional["BooleanState"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareFeatureControlState(IntEnum):
    DISABLED = 1
    ENABLED = 2

class SquareFeatureSet(BaseModel):
    square_mid: Optional[str] = Field(alias="1", default=None)
    revision: int = Field(alias="2", default=0)
    creating_secret_square_chat: Optional["SquareFeature"] = Field(alias="11", default=None)
    inviting_into_open_square_chat: Optional["SquareFeature"] = Field(alias="12", default=None)
    creating_square_chat: Optional["SquareFeature"] = Field(alias="13", default=None)
    readonly_default_chat: Optional["SquareFeature"] = Field(alias="14", default=None)
    showing_advertisement: Optional["SquareFeature"] = Field(alias="15", default=None)
    delegate_join_to_plug: Optional["SquareFeature"] = Field(alias="16", default=None)
    delegate_kick_out_to_plug: Optional["SquareFeature"] = Field(alias="17", default=None)
    disable_update_join_method: Optional["SquareFeature"] = Field(alias="18", default=None)
    disable_transfer_admin: Optional["SquareFeature"] = Field(alias="19", default=None)
    creating_live_talk: Optional["SquareFeature"] = Field(alias="20", default=None)
    disable_update_searchable: Optional["SquareFeature"] = Field(alias="21", default=None)

    class Config:
        populate_by_name = True

class SquareJoinMethod(BaseModel):
    type_: Optional["SquareJoinMethodType"] = Field(alias="1", default=None)
    value: Optional["SquareJoinMethodValue"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareJoinMethodType(IntEnum):
    NONE = 0
    APPROVAL = 1
    CODE = 2

class SquareJoinMethodValue(BaseModel):
    approval_value: Optional["ApprovalValue"] = Field(alias="1", default=None)
    code_value: Optional["CodeValue"] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True

class SquareMember(BaseModel):
    square_member_mid: Optional[str] = Field(alias="1", default=None)
    square_mid: Optional[str] = Field(alias="2", default=None)
    display_name: Optional[str] = Field(alias="3", default=None)
    profile_image_obs_hash: Optional[str] = Field(alias="4", default=None)
    able_to_receive_message: bool = Field(alias="5", default=False)
    membership_state: Optional["SquareMembershipState"] = Field(alias="7", default=None)
    role: Optional["SquareMemberRole"] = Field(alias="8", default=None)
    revision: int = Field(alias="9", default=0)
    preference: Optional["SquarePreference"] = Field(alias="10", default=None)
    join_message: Optional[str] = Field(alias="11", default=None)

    class Config:
        populate_by_name = True

class SquareMemberRelation(BaseModel):
    state: Optional["SquareMemberRelationState"] = Field(alias="1", default=None)
    revision: int = Field(alias="2", default=0)

    class Config:
        populate_by_name = True

class SquareMemberRelationState(IntEnum):
    NONE = 1
    BLOCKED = 2

class SquareMemberRole(IntEnum):
    ADMIN = 1
    CO_ADMIN = 2
    MEMBER = 10

class SquareMembershipState(IntEnum):
    JOIN_REQUESTED = 1
    JOINED = 2
    REJECTED = 3
    LEFT = 4
    KICK_OUT = 5
    BANNED = 6
    DELETED = 7

class SquareMessage(BaseModel):
    message: Optional[Any] = Field(alias="1", default=None)
    from_type: Optional[Any] = Field(alias="3", default=None)
    square_message_revision: int = Field(alias="4", default=0)
    state: Optional["SquareMessageState"] = Field(alias="5", default=None)
    thread_info: Optional["SquareMessageThreadInfo"] = Field(alias="6", default=None)

    class Config:
        populate_by_name = True

class SquareMessageReaction(BaseModel):
    type_: Optional[Any] = Field(alias="1", default=None)
    reactor: Optional["SquareMember"] = Field(alias="2", default=None)
    created_at: int = Field(alias="3", default=0)
    updated_at: int = Field(alias="4", default=0)

    class Config:
        populate_by_name = True

class SquareMessageReactionStatus(BaseModel):
    total_count: int = Field(alias="1", default=0)
    count_by_reaction_type: Dict[Any, int] = Field(alias="2", default_factory=dict)
    my_reaction: Optional["SquareMessageReaction"] = Field(alias="3", default=None)

    class Config:
        populate_by_name = True

class SquareMessageState(IntEnum):
    SENT = 1
    DELETED = 2
    FORBIDDEN = 3
    UNSENT = 4

class SquareMessageStatus(BaseModel):
    square_chat_mid: Optional[str] = Field(alias="1", default=None)
    global_message_id: Optional[str] = Field(alias="2", default=None)
    type_: Optional["MessageStatusType"] = Field(alias="3", default=None)
    contents: Optional["MessageStatusContents"] = Field(alias="4", default=None)
    published_at: int = Field(alias="5", default=0)

    class Config:
        populate_by_name = True

class SquareMessageThreadInfo(BaseModel):
    chat_thread_mid: Optional[str] = Field(alias="1", default=None)
    thread_root: bool = Field(alias="2", default=False)

    class Config:
        populate_by_name = True

class SquarePreference(BaseModel):
    favorite_timestamp: int = Field(alias="1", default=0)
    noti_for_new_join_request: bool = Field(alias="2", default=False)

    class Config:
        populate_by_name = True

class SquareState(IntEnum):
    ALIVE = 0
    DELETED = 1
    SUSPENDED = 2

class SquareStatus(BaseModel):
    member_count: int = Field(alias="1", default=0)
    join_request_count: int = Field(alias="2", default=0)
    last_join_request_at: int = Field(alias="3", default=0)
    open_chat_count: int = Field(alias="4", default=0)

    class Config:
        populate_by_name = True

class SquareThread(BaseModel):
    thread_mid: Optional[str] = Field(alias="1", default=None)
    chat_mid: Optional[str] = Field(alias="2", default=None)
    square_mid: Optional[str] = Field(alias="3", default=None)
    message_id: Optional[str] = Field(alias="4", default=None)
    state: Optional["SquareThreadState"] = Field(alias="5", default=None)
    expires_at: int = Field(alias="6", default=0)
    read_only_at: int = Field(alias="7", default=0)
    revision: int = Field(alias="8", default=0)

    class Config:
        populate_by_name = True

class SquareThreadMember(BaseModel):
    square_member_mid: Optional[str] = Field(alias="1", default=None)
    thread_mid: Optional[str] = Field(alias="2", default=None)
    chat_mid: Optional[str] = Field(alias="3", default=None)
    revision: int = Field(alias="4", default=0)
    membership_state: Optional["SquareThreadMembershipState"] = Field(alias="5", default=None)

    class Config:
        populate_by_name = True

class SquareThreadMembershipState(IntEnum):
    JOINED = 1
    LEFT = 2

class SquareThreadState(IntEnum):
    ALIVE = 1
    DELETED = 2

class SquareType(IntEnum):
    CLOSED = 0
    OPEN = 1

class StatusBadge(IntEnum):
    LIVETALK_ONAIR = 1

class SubscriptionState(BaseModel):
    subscription_id: int = Field(alias="1", default=0)
    ttl_millis: int = Field(alias="2", default=0)

    class Config:
        populate_by_name = True

class SyncSquareMembersResponse(BaseModel):
    updated_square_members: List["SquareMember"] = Field(alias="1", default_factory=list)

    class Config:
        populate_by_name = True

class TextButton(BaseModel):
    text: Optional[str] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class TextMessageAnnouncementContents(BaseModel):
    message_id: Optional[str] = Field(alias="1", default=None)
    text: Optional[str] = Field(alias="2", default=None)
    sender_square_member_mid: Optional[str] = Field(alias="3", default=None)
    created_at: int = Field(alias="4", default=0)
    sender_mid: Optional[str] = Field(alias="5", default=None)

    class Config:
        populate_by_name = True

class UnsendMessageResponse(BaseModel):
    unsent_message: Optional["SquareMessage"] = Field(alias="1", default=None)

    class Config:
        populate_by_name = True

class UrlButton(BaseModel):
    text: Optional[str] = Field(alias="1", default=None)
    url: Optional[str] = Field(alias="2", default=None)

    class Config:
        populate_by_name = True
