# -*- coding: utf-8 -*-
# AUTO-GENERATED BY tools/generate_models.py
from typing import List, Optional, Dict, Any
from .services.base import ServiceBase
from .models.square import *


class SquareService(ServiceBase):
    ENDPOINT = "/SQ1"
    PROTOCOL = 4

    def accept_speakers(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        target_mids: Optional[List[str]] = None,
    ) -> AcceptSpeakersResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if target_mids is not None:
            params.append([14, 3, target_mids])
        return self._call(
            "acceptSpeakers", [[12, 1, params]], response_model=AcceptSpeakersResponse
        )

    def accept_to_change_role(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        invite_request_id: Optional[str] = None,
    ) -> AcceptToChangeRoleResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if invite_request_id is not None:
            params.append([11, 3, invite_request_id])
        return self._call(
            "acceptToChangeRole",
            [[12, 1, params]],
            response_model=AcceptToChangeRoleResponse,
        )

    def accept_to_listen(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        invite_request_id: Optional[str] = None,
    ) -> AcceptToListenResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if invite_request_id is not None:
            params.append([11, 3, invite_request_id])
        return self._call(
            "acceptToListen", [[12, 1, params]], response_model=AcceptToListenResponse
        )

    def accept_to_speak(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        invite_request_id: Optional[str] = None,
    ) -> AcceptToSpeakResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if invite_request_id is not None:
            params.append([11, 3, invite_request_id])
        return self._call(
            "acceptToSpeak", [[12, 1, params]], response_model=AcceptToSpeakResponse
        )

    def acquire_live_talk(
        self,
        square_chat_mid: Optional[str] = None,
        title: Optional[str] = None,
        type: Optional["LiveTalkType"] = None,
        speaker_setting: Optional["LiveTalkSpeakerSetting"] = None,
    ) -> AcquireLiveTalkResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if title is not None:
            params.append([11, 2, title])
        if type is not None:
            params.append([10, 3, type])
        if speaker_setting is not None:
            params.append([10, 4, speaker_setting])
        return self._call(
            "acquireLiveTalk", [[12, 1, params]], response_model=AcquireLiveTalkResponse
        )

    def agree_to_terms(
        self,
        terms_type: Optional[Any] = None,
        terms_agreement: Optional["TermsAgreement"] = None,
    ) -> AgreeToTermsResponse:
        params = []
        if terms_type is not None:
            params.append([12, 1, terms_type])
        if terms_agreement is not None:
            params.append([12, 2, terms_agreement])
        return self._call(
            "agreeToTerms", [[12, 1, params]], response_model=AgreeToTermsResponse
        )

    def approve_square_members(
        self,
        square_mid: Optional[str] = None,
        requested_member_mids: Optional[List[str]] = None,
    ) -> ApproveSquareMembersResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        if requested_member_mids is not None:
            params.append([15, 3, requested_member_mids])
        return self._call(
            "approveSquareMembers",
            [[12, 1, params]],
            response_model=ApproveSquareMembersResponse,
        )

    def cancel_to_speak(
        self, square_chat_mid: Optional[str] = None, session_id: Optional[str] = None
    ) -> CancelToSpeakResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        return self._call(
            "cancelToSpeak", [[12, 1, params]], response_model=CancelToSpeakResponse
        )

    def check_join_code(
        self, square_mid: Optional[str] = None, join_code: Optional[str] = None
    ) -> CheckJoinCodeResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        if join_code is not None:
            params.append([11, 3, join_code])
        return self._call(
            "checkJoinCode", [[12, 1, params]], response_model=CheckJoinCodeResponse
        )

    def create_square(
        self,
        req_seq: Optional[int] = None,
        square: Optional["Square"] = None,
        creator: Optional["SquareMember"] = None,
    ) -> CreateSquareResponse:
        params = []
        if req_seq is not None:
            params.append([8, 1, req_seq])
        if square is not None:
            params.append([12, 2, square])
        if creator is not None:
            params.append([12, 3, creator])
        return self._call(
            "createSquare", [[12, 1, params]], response_model=CreateSquareResponse
        )

    def create_square_chat(
        self,
        req_seq: Optional[int] = None,
        square_chat: Optional["SquareChat"] = None,
        square_member_mids: Optional[List[str]] = None,
    ) -> CreateSquareChatResponse:
        params = []
        if req_seq is not None:
            params.append([8, 1, req_seq])
        if square_chat is not None:
            params.append([12, 2, square_chat])
        if square_member_mids is not None:
            params.append([15, 3, square_member_mids])
        return self._call(
            "createSquareChat",
            [[12, 1, params]],
            response_model=CreateSquareChatResponse,
        )

    def delete_square(
        self, mid: Optional[str] = None, revision: Optional[int] = None
    ) -> DeleteSquareResponse:
        params = []
        if mid is not None:
            params.append([11, 2, mid])
        if revision is not None:
            params.append([10, 3, revision])
        return self._call(
            "deleteSquare", [[12, 1, params]], response_model=DeleteSquareResponse
        )

    def delete_square_chat(
        self, square_chat_mid: Optional[str] = None, revision: Optional[int] = None
    ) -> DeleteSquareChatResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 2, square_chat_mid])
        if revision is not None:
            params.append([10, 3, revision])
        return self._call(
            "deleteSquareChat",
            [[12, 1, params]],
            response_model=DeleteSquareChatResponse,
        )

    def destroy_message(
        self,
        square_chat_mid: Optional[str] = None,
        message_id: Optional[str] = None,
        thread_mid: Optional[str] = None,
    ) -> DestroyMessageResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 2, square_chat_mid])
        if message_id is not None:
            params.append([11, 4, message_id])
        if thread_mid is not None:
            params.append([11, 5, thread_mid])
        return self._call(
            "destroyMessage", [[12, 1, params]], response_model=DestroyMessageResponse
        )

    def destroy_messages(
        self,
        square_chat_mid: Optional[str] = None,
        message_ids: Optional[List[str]] = None,
        thread_mid: Optional[str] = None,
    ) -> DestroyMessagesResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 2, square_chat_mid])
        if message_ids is not None:
            params.append([14, 4, message_ids])
        if thread_mid is not None:
            params.append([11, 5, thread_mid])
        return self._call(
            "destroyMessages", [[12, 1, params]], response_model=DestroyMessagesResponse
        )

    def fetch_live_talk_events(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        sync_token: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> FetchLiveTalkEventsResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if sync_token is not None:
            params.append([11, 3, sync_token])
        if limit is not None:
            params.append([8, 4, limit])
        return self._call(
            "fetchLiveTalkEvents",
            [[12, 1, params]],
            response_model=FetchLiveTalkEventsResponse,
        )

    def fetch_my_events(
        self,
        subscription_id: Optional[int] = None,
        sync_token: Optional[str] = None,
        limit: Optional[int] = None,
        continuation_token: Optional[str] = None,
    ) -> FetchMyEventsResponse:
        params = []
        if subscription_id is not None:
            params.append([10, 1, subscription_id])
        if sync_token is not None:
            params.append([11, 2, sync_token])
        if limit is not None:
            params.append([8, 3, limit])
        if continuation_token is not None:
            params.append([11, 4, continuation_token])
        return self._call(
            "fetchMyEvents", [[12, 1, params]], response_model=FetchMyEventsResponse
        )

    def fetch_square_chat_events(
        self,
        subscription_id: Optional[int] = None,
        square_chat_mid: Optional[str] = None,
        sync_token: Optional[str] = None,
        limit: Optional[int] = None,
        direction: Optional["FetchDirection"] = None,
        inclusive: Optional["BooleanState"] = None,
        continuation_token: Optional[str] = None,
        fetch_type: Optional["FetchType"] = None,
        thread_mid: Optional[str] = None,
    ) -> FetchSquareChatEventsResponse:
        params = []
        if subscription_id is not None:
            params.append([10, 1, subscription_id])
        if square_chat_mid is not None:
            params.append([11, 2, square_chat_mid])
        if sync_token is not None:
            params.append([11, 3, sync_token])
        if limit is not None:
            params.append([8, 4, limit])
        if direction is not None:
            params.append([10, 5, direction])
        if inclusive is not None:
            params.append([10, 6, inclusive])
        if continuation_token is not None:
            params.append([11, 7, continuation_token])
        if fetch_type is not None:
            params.append([10, 8, fetch_type])
        if thread_mid is not None:
            params.append([11, 9, thread_mid])
        return self._call(
            "fetchSquareChatEvents",
            [[12, 1, params]],
            response_model=FetchSquareChatEventsResponse,
        )

    def find_live_talk_by_invitation_ticket(
        self, invitation_ticket: Optional[str] = None
    ) -> FindLiveTalkByInvitationTicketResponse:
        params = []
        if invitation_ticket is not None:
            params.append([11, 1, invitation_ticket])
        return self._call(
            "findLiveTalkByInvitationTicket",
            [[12, 1, params]],
            response_model=FindLiveTalkByInvitationTicketResponse,
        )

    def find_square_by_invitation_ticket(
        self, invitation_ticket: Optional[str] = None
    ) -> FindSquareByInvitationTicketResponse:
        params = []
        if invitation_ticket is not None:
            params.append([11, 2, invitation_ticket])
        return self._call(
            "findSquareByInvitationTicket",
            [[12, 1, params]],
            response_model=FindSquareByInvitationTicketResponse,
        )

    def find_square_by_invitation_ticket_v2(
        self, invitation_ticket: Optional[str] = None
    ) -> FindSquareByInvitationTicketV2Response:
        params = []
        if invitation_ticket is not None:
            params.append([11, 1, invitation_ticket])
        return self._call(
            "findSquareByInvitationTicketV2",
            [[12, 1, params]],
            response_model=FindSquareByInvitationTicketV2Response,
        )

    def force_end_live_talk(
        self, square_chat_mid: Optional[str] = None, session_id: Optional[str] = None
    ) -> ForceEndLiveTalkResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        return self._call(
            "forceEndLiveTalk",
            [[12, 1, params]],
            response_model=ForceEndLiveTalkResponse,
        )

    def get_categories(self) -> GetSquareCategoriesResponse:
        params = []
        return self._call(
            "getCategories",
            [[12, 1, params]],
            response_model=GetSquareCategoriesResponse,
        )

    def get_google_ad_options(
        self,
        square_mid: Optional[str] = None,
        chat_mid: Optional[str] = None,
        ad_screen: Optional["AdScreen"] = None,
    ) -> GetGoogleAdOptionsResponse:
        params = []
        if square_mid is not None:
            params.append([11, 1, square_mid])
        if chat_mid is not None:
            params.append([11, 2, chat_mid])
        if ad_screen is not None:
            params.append([10, 3, ad_screen])
        return self._call(
            "getGoogleAdOptions",
            [[12, 1, params]],
            response_model=GetGoogleAdOptionsResponse,
        )

    def get_invitation_ticket_url(
        self, mid: Optional[str] = None
    ) -> GetInvitationTicketUrlResponse:
        params = []
        if mid is not None:
            params.append([11, 2, mid])
        return self._call(
            "getInvitationTicketUrl",
            [[12, 1, params]],
            response_model=GetInvitationTicketUrlResponse,
        )

    def get_joinable_square_chats(
        self,
        square_mid: Optional[str] = None,
        continuation_token: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> GetJoinableSquareChatsResponse:
        params = []
        if square_mid is not None:
            params.append([11, 1, square_mid])
        if continuation_token is not None:
            params.append([11, 10, continuation_token])
        if limit is not None:
            params.append([8, 11, limit])
        return self._call(
            "getJoinableSquareChats",
            [[12, 1, params]],
            response_model=GetJoinableSquareChatsResponse,
        )

    def get_joined_square_chats(
        self, continuation_token: Optional[str] = None, limit: Optional[int] = None
    ) -> GetJoinedSquareChatsResponse:
        params = []
        if continuation_token is not None:
            params.append([11, 2, continuation_token])
        if limit is not None:
            params.append([8, 3, limit])
        return self._call(
            "getJoinedSquareChats",
            [[12, 1, params]],
            response_model=GetJoinedSquareChatsResponse,
        )

    def get_joined_squares(
        self, continuation_token: Optional[str] = None, limit: Optional[int] = None
    ) -> GetJoinedSquaresResponse:
        params = []
        if continuation_token is not None:
            params.append([11, 2, continuation_token])
        if limit is not None:
            params.append([8, 3, limit])
        return self._call(
            "getJoinedSquares",
            [[12, 1, params]],
            response_model=GetJoinedSquaresResponse,
        )

    def get_live_talk_info_for_non_member(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        speakers: Optional[List[str]] = None,
    ) -> GetLiveTalkInfoForNonMemberResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if speakers is not None:
            params.append([15, 3, speakers])
        return self._call(
            "getLiveTalkInfoForNonMember",
            [[12, 1, params]],
            response_model=GetLiveTalkInfoForNonMemberResponse,
        )

    def get_live_talk_invitation_url(
        self, square_chat_mid: Optional[str] = None, session_id: Optional[str] = None
    ) -> GetLiveTalkInvitationUrlResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        return self._call(
            "getLiveTalkInvitationUrl",
            [[12, 1, params]],
            response_model=GetLiveTalkInvitationUrlResponse,
        )

    def get_live_talk_speakers_for_non_member(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        speakers: Optional[List[str]] = None,
    ) -> GetLiveTalkSpeakersForNonMemberResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if speakers is not None:
            params.append([15, 3, speakers])
        return self._call(
            "getLiveTalkSpeakersForNonMember",
            [[12, 1, params]],
            response_model=GetLiveTalkSpeakersForNonMemberResponse,
        )

    def get_message_reactions(
        self,
        square_chat_mid: Optional[str] = None,
        message_id: Optional[str] = None,
        type: Optional["MessageReactionType"] = None,
        continuation_token: Optional[str] = None,
        limit: Optional[int] = None,
        thread_mid: Optional[str] = None,
    ) -> GetMessageReactionsResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if message_id is not None:
            params.append([11, 2, message_id])
        if type is not None:
            params.append([10, 3, type])
        if continuation_token is not None:
            params.append([11, 4, continuation_token])
        if limit is not None:
            params.append([8, 5, limit])
        if thread_mid is not None:
            params.append([11, 6, thread_mid])
        return self._call(
            "getMessageReactions",
            [[12, 1, params]],
            response_model=GetMessageReactionsResponse,
        )

    def get_note_status(
        self, square_mid: Optional[str] = None
    ) -> GetNoteStatusResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        return self._call(
            "getNoteStatus", [[12, 1, params]], response_model=GetNoteStatusResponse
        )

    def get_popular_keywords(self) -> GetPopularKeywordsResponse:
        params = []
        return self._call(
            "getPopularKeywords",
            [[12, 1, params]],
            response_model=GetPopularKeywordsResponse,
        )

    def get_square(self, mid: Optional[str] = None) -> GetSquareResponse:
        params = []
        if mid is not None:
            params.append([11, 2, mid])
        return self._call(
            "getSquare", [[12, 1, params]], response_model=GetSquareResponse
        )

    def get_square_authorities(
        self, square_mids: Optional[List[str]] = None
    ) -> GetSquareAuthoritiesResponse:
        params = []
        if square_mids is not None:
            params.append([14, 2, square_mids])
        return self._call(
            "getSquareAuthorities",
            [[12, 1, params]],
            response_model=GetSquareAuthoritiesResponse,
        )

    def get_square_authority(
        self, square_mid: Optional[str] = None
    ) -> GetSquareAuthorityResponse:
        params = []
        if square_mid is not None:
            params.append([11, 1, square_mid])
        return self._call(
            "getSquareAuthority",
            [[12, 1, params]],
            response_model=GetSquareAuthorityResponse,
        )

    def get_square_chat(
        self, square_chat_mid: Optional[str] = None
    ) -> GetSquareChatResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        return self._call(
            "getSquareChat", [[12, 1, params]], response_model=GetSquareChatResponse
        )

    def get_square_chat_emid(
        self, square_chat_mid: Optional[str] = None
    ) -> GetSquareChatEmidResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        return self._call(
            "getSquareChatEmid",
            [[12, 1, params]],
            response_model=GetSquareChatEmidResponse,
        )

    def get_square_chat_feature_set(
        self, square_chat_mid: Optional[str] = None
    ) -> GetSquareChatFeatureSetResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 2, square_chat_mid])
        return self._call(
            "getSquareChatFeatureSet",
            [[12, 1, params]],
            response_model=GetSquareChatFeatureSetResponse,
        )

    def get_square_chat_member(
        self,
        square_member_mid: Optional[str] = None,
        square_chat_mid: Optional[str] = None,
    ) -> GetSquareChatMemberResponse:
        params = []
        if square_member_mid is not None:
            params.append([11, 2, square_member_mid])
        if square_chat_mid is not None:
            params.append([11, 3, square_chat_mid])
        return self._call(
            "getSquareChatMember",
            [[12, 1, params]],
            response_model=GetSquareChatMemberResponse,
        )

    def get_square_chat_members(
        self,
        square_chat_mid: Optional[str] = None,
        continuation_token: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> GetSquareChatMembersResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if continuation_token is not None:
            params.append([11, 2, continuation_token])
        if limit is not None:
            params.append([8, 3, limit])
        return self._call(
            "getSquareChatMembers",
            [[12, 1, params]],
            response_model=GetSquareChatMembersResponse,
        )

    def get_square_chat_status(
        self, square_chat_mid: Optional[str] = None
    ) -> GetSquareChatStatusResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 2, square_chat_mid])
        return self._call(
            "getSquareChatStatus",
            [[12, 1, params]],
            response_model=GetSquareChatStatusResponse,
        )

    def get_square_emid(
        self, square_mid: Optional[str] = None
    ) -> GetSquareEmidResponse:
        params = []
        if square_mid is not None:
            params.append([11, 1, square_mid])
        return self._call(
            "getSquareEmid", [[12, 1, params]], response_model=GetSquareEmidResponse
        )

    def get_square_feature_set(
        self, square_mid: Optional[str] = None
    ) -> GetSquareFeatureSetResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        return self._call(
            "getSquareFeatureSet",
            [[12, 1, params]],
            response_model=GetSquareFeatureSetResponse,
        )

    def get_square_info_by_chat_mid(
        self, square_chat_mid: Optional[str] = None
    ) -> GetSquareInfoByChatMidResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        return self._call(
            "getSquareInfoByChatMid",
            [[12, 1, params]],
            response_model=GetSquareInfoByChatMidResponse,
        )

    def get_square_member(
        self, square_member_mid: Optional[str] = None
    ) -> GetSquareMemberResponse:
        params = []
        if square_member_mid is not None:
            params.append([11, 2, square_member_mid])
        return self._call(
            "getSquareMember", [[12, 1, params]], response_model=GetSquareMemberResponse
        )

    def get_square_member_relation(
        self,
        square_mid: Optional[str] = None,
        target_square_member_mid: Optional[str] = None,
    ) -> GetSquareMemberRelationResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        if target_square_member_mid is not None:
            params.append([11, 3, target_square_member_mid])
        return self._call(
            "getSquareMemberRelation",
            [[12, 1, params]],
            response_model=GetSquareMemberRelationResponse,
        )

    def get_square_member_relations(
        self,
        state: Optional["SquareMemberRelationState"] = None,
        continuation_token: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> GetSquareMemberRelationsResponse:
        params = []
        if state is not None:
            params.append([10, 2, state])
        if continuation_token is not None:
            params.append([11, 3, continuation_token])
        if limit is not None:
            params.append([8, 4, limit])
        return self._call(
            "getSquareMemberRelations",
            [[12, 1, params]],
            response_model=GetSquareMemberRelationsResponse,
        )

    def get_square_members(
        self, mids: Optional[List[str]] = None
    ) -> GetSquareMembersResponse:
        params = []
        if mids is not None:
            params.append([14, 2, mids])
        return self._call(
            "getSquareMembers",
            [[12, 1, params]],
            response_model=GetSquareMembersResponse,
        )

    def get_square_members_by_square(
        self,
        square_mid: Optional[str] = None,
        square_member_mids: Optional[List[str]] = None,
    ) -> GetSquareMembersBySquareResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        if square_member_mids is not None:
            params.append([14, 3, square_member_mids])
        return self._call(
            "getSquareMembersBySquare",
            [[12, 1, params]],
            response_model=GetSquareMembersBySquareResponse,
        )

    def get_square_status(
        self, square_mid: Optional[str] = None
    ) -> GetSquareStatusResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        return self._call(
            "getSquareStatus", [[12, 1, params]], response_model=GetSquareStatusResponse
        )

    def get_square_thread(
        self,
        thread_mid: Optional[str] = None,
        include_root_message: Optional[bool] = None,
    ) -> GetSquareThreadResponse:
        params = []
        if thread_mid is not None:
            params.append([11, 1, thread_mid])
        if include_root_message is not None:
            params.append([2, 2, include_root_message])
        return self._call(
            "getSquareThread", [[12, 1, params]], response_model=GetSquareThreadResponse
        )

    def get_square_thread_mid(
        self, chat_mid: Optional[str] = None, message_id: Optional[str] = None
    ) -> GetSquareThreadMidResponse:
        params = []
        if chat_mid is not None:
            params.append([11, 1, chat_mid])
        if message_id is not None:
            params.append([11, 2, message_id])
        return self._call(
            "getSquareThreadMid",
            [[12, 1, params]],
            response_model=GetSquareThreadMidResponse,
        )

    def get_user_settings(
        self, requested_attrs: Optional[List[Any]] = None
    ) -> GetUserSettingsResponse:
        params = []
        if requested_attrs is not None:
            params.append([14, 1, requested_attrs])
        return self._call(
            "getUserSettings", [[12, 1, params]], response_model=GetUserSettingsResponse
        )

    def hide_square_member_contents(
        self, square_member_mid: Optional[str] = None
    ) -> HideSquareMemberContentsResponse:
        params = []
        if square_member_mid is not None:
            params.append([11, 1, square_member_mid])
        return self._call(
            "hideSquareMemberContents",
            [[12, 1, params]],
            response_model=HideSquareMemberContentsResponse,
        )

    def invite_into_square_chat(
        self,
        invitee_mids: Optional[List[str]] = None,
        square_chat_mid: Optional[str] = None,
    ) -> InviteIntoSquareChatResponse:
        params = []
        if invitee_mids is not None:
            params.append([15, 1, invitee_mids])
        if square_chat_mid is not None:
            params.append([11, 2, square_chat_mid])
        return self._call(
            "inviteIntoSquareChat",
            [[12, 1, params]],
            response_model=InviteIntoSquareChatResponse,
        )

    def invite_to_change_role(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        target_mid: Optional[str] = None,
        target_role: Optional["LiveTalkRole"] = None,
    ) -> InviteToChangeRoleResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if target_mid is not None:
            params.append([11, 3, target_mid])
        if target_role is not None:
            params.append([10, 4, target_role])
        return self._call(
            "inviteToChangeRole",
            [[12, 1, params]],
            response_model=InviteToChangeRoleResponse,
        )

    def invite_to_listen(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        target_mid: Optional[str] = None,
    ) -> InviteToListenResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if target_mid is not None:
            params.append([11, 3, target_mid])
        return self._call(
            "inviteToListen", [[12, 1, params]], response_model=InviteToListenResponse
        )

    def invite_to_live_talk(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        invitees: Optional[List[str]] = None,
    ) -> InviteToLiveTalkResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if invitees is not None:
            params.append([15, 3, invitees])
        return self._call(
            "inviteToLiveTalk",
            [[12, 1, params]],
            response_model=InviteToLiveTalkResponse,
        )

    def invite_to_speak(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        target_mid: Optional[str] = None,
    ) -> InviteToSpeakResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if target_mid is not None:
            params.append([11, 3, target_mid])
        return self._call(
            "inviteToSpeak", [[12, 1, params]], response_model=InviteToSpeakResponse
        )

    def invite_to_square(
        self,
        square_mid: Optional[str] = None,
        invitees: Optional[List[str]] = None,
        square_chat_mid: Optional[str] = None,
    ) -> InviteToSquareResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        if invitees is not None:
            params.append([15, 3, invitees])
        if square_chat_mid is not None:
            params.append([11, 4, square_chat_mid])
        return self._call(
            "inviteToSquare", [[12, 1, params]], response_model=InviteToSquareResponse
        )

    def join_live_talk(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        want_to_speak: Optional[bool] = None,
        claim_adult: Optional["BooleanState"] = None,
    ) -> JoinLiveTalkResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if want_to_speak is not None:
            params.append([2, 3, want_to_speak])
        if claim_adult is not None:
            params.append([10, 4, claim_adult])
        return self._call(
            "joinLiveTalk", [[12, 1, params]], response_model=JoinLiveTalkResponse
        )

    def join_square(
        self,
        square_mid: Optional[str] = None,
        member: Optional["SquareMember"] = None,
        square_chat_mid: Optional[str] = None,
        join_value: Optional["SquareJoinMethodValue"] = None,
        claim_adult: Optional["BooleanState"] = None,
    ) -> JoinSquareResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        if member is not None:
            params.append([12, 3, member])
        if square_chat_mid is not None:
            params.append([11, 4, square_chat_mid])
        if join_value is not None:
            params.append([12, 5, join_value])
        if claim_adult is not None:
            params.append([10, 6, claim_adult])
        return self._call(
            "joinSquare", [[12, 1, params]], response_model=JoinSquareResponse
        )

    def join_square_chat(
        self, square_chat_mid: Optional[str] = None
    ) -> JoinSquareChatResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        return self._call(
            "joinSquareChat", [[12, 1, params]], response_model=JoinSquareChatResponse
        )

    def join_square_thread(
        self, chat_mid: Optional[str] = None, thread_mid: Optional[str] = None
    ) -> JoinSquareThreadResponse:
        params = []
        if chat_mid is not None:
            params.append([11, 1, chat_mid])
        if thread_mid is not None:
            params.append([11, 2, thread_mid])
        return self._call(
            "joinSquareThread",
            [[12, 1, params]],
            response_model=JoinSquareThreadResponse,
        )

    def kick_out_live_talk_participants(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        target: Optional["LiveTalkKickOutTarget"] = None,
    ) -> KickOutLiveTalkParticipantsResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if target is not None:
            params.append([12, 3, target])
        return self._call(
            "kickOutLiveTalkParticipants",
            [[12, 1, params]],
            response_model=KickOutLiveTalkParticipantsResponse,
        )

    def leave_square(self, square_mid: Optional[str] = None) -> LeaveSquareResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        return self._call(
            "leaveSquare", [[12, 1, params]], response_model=LeaveSquareResponse
        )

    def leave_square_chat(
        self,
        square_chat_mid: Optional[str] = None,
        say_goodbye: Optional[bool] = None,
        square_chat_member_revision: Optional[int] = None,
    ) -> LeaveSquareChatResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 2, square_chat_mid])
        if say_goodbye is not None:
            params.append([2, 3, say_goodbye])
        if square_chat_member_revision is not None:
            params.append([10, 4, square_chat_member_revision])
        return self._call(
            "leaveSquareChat", [[12, 1, params]], response_model=LeaveSquareChatResponse
        )

    def leave_square_thread(
        self, chat_mid: Optional[str] = None, thread_mid: Optional[str] = None
    ) -> LeaveSquareThreadResponse:
        params = []
        if chat_mid is not None:
            params.append([11, 1, chat_mid])
        if thread_mid is not None:
            params.append([11, 2, thread_mid])
        return self._call(
            "leaveSquareThread",
            [[12, 1, params]],
            response_model=LeaveSquareThreadResponse,
        )

    def manual_repair(
        self,
        sync_token: Optional[str] = None,
        limit: Optional[int] = None,
        continuation_token: Optional[str] = None,
    ) -> ManualRepairResponse:
        params = []
        if sync_token is not None:
            params.append([11, 1, sync_token])
        if limit is not None:
            params.append([8, 2, limit])
        if continuation_token is not None:
            params.append([11, 3, continuation_token])
        return self._call(
            "manualRepair", [[12, 1, params]], response_model=ManualRepairResponse
        )

    def mark_as_read(
        self,
        square_chat_mid: Optional[str] = None,
        message_id: Optional[str] = None,
        thread_mid: Optional[str] = None,
    ) -> MarkAsReadResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 2, square_chat_mid])
        if message_id is not None:
            params.append([11, 4, message_id])
        if thread_mid is not None:
            params.append([11, 5, thread_mid])
        return self._call(
            "markAsRead", [[12, 1, params]], response_model=MarkAsReadResponse
        )

    def mark_chats_as_read(
        self, chat_mids: Optional[List[str]] = None
    ) -> MarkChatsAsReadResponse:
        params = []
        if chat_mids is not None:
            params.append([14, 2, chat_mids])
        return self._call(
            "markChatsAsRead", [[12, 1, params]], response_model=MarkChatsAsReadResponse
        )

    def mark_threads_as_read(
        self, chat_mid: Optional[str] = None
    ) -> MarkThreadsAsReadResponse:
        params = []
        if chat_mid is not None:
            params.append([11, 1, chat_mid])
        return self._call(
            "markThreadsAsRead",
            [[12, 1, params]],
            response_model=MarkThreadsAsReadResponse,
        )

    def react_to_message(
        self,
        req_seq: Optional[int] = None,
        square_chat_mid: Optional[str] = None,
        message_id: Optional[str] = None,
        reaction_type: Optional["MessageReactionType"] = None,
        thread_mid: Optional[str] = None,
    ) -> ReactToMessageResponse:
        params = []
        if req_seq is not None:
            params.append([8, 1, req_seq])
        if square_chat_mid is not None:
            params.append([11, 2, square_chat_mid])
        if message_id is not None:
            params.append([11, 3, message_id])
        if reaction_type is not None:
            params.append([10, 4, reaction_type])
        if thread_mid is not None:
            params.append([11, 5, thread_mid])
        return self._call(
            "reactToMessage", [[12, 1, params]], response_model=ReactToMessageResponse
        )

    def refresh_subscriptions(
        self, subscriptions: Optional[List[int]] = None
    ) -> RefreshSubscriptionsResponse:
        params = []
        if subscriptions is not None:
            params.append([15, 2, subscriptions])
        return self._call(
            "refreshSubscriptions",
            [[12, 1, params]],
            response_model=RefreshSubscriptionsResponse,
        )

    def reject_speakers(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        target_mids: Optional[List[str]] = None,
    ) -> RejectSpeakersResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if target_mids is not None:
            params.append([14, 3, target_mids])
        return self._call(
            "rejectSpeakers", [[12, 1, params]], response_model=RejectSpeakersResponse
        )

    def reject_square_members(
        self,
        square_mid: Optional[str] = None,
        requested_member_mids: Optional[List[str]] = None,
    ) -> RejectSquareMembersResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        if requested_member_mids is not None:
            params.append([15, 3, requested_member_mids])
        return self._call(
            "rejectSquareMembers",
            [[12, 1, params]],
            response_model=RejectSquareMembersResponse,
        )

    def reject_to_speak(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        invite_request_id: Optional[str] = None,
    ) -> RejectToSpeakResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if invite_request_id is not None:
            params.append([11, 3, invite_request_id])
        return self._call(
            "rejectToSpeak", [[12, 1, params]], response_model=RejectToSpeakResponse
        )

    def remove_live_talk_subscription(
        self, square_chat_mid: Optional[str] = None, session_id: Optional[str] = None
    ) -> RemoveLiveTalkSubscriptionResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        return self._call(
            "removeLiveTalkSubscription",
            [[12, 1, params]],
            response_model=RemoveLiveTalkSubscriptionResponse,
        )

    def remove_subscriptions(
        self, unsubscriptions: Optional[List[int]] = None
    ) -> RemoveSubscriptionsResponse:
        params = []
        if unsubscriptions is not None:
            params.append([15, 2, unsubscriptions])
        return self._call(
            "removeSubscriptions",
            [[12, 1, params]],
            response_model=RemoveSubscriptionsResponse,
        )

    def report_live_talk(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        report_type: Optional["LiveTalkReportType"] = None,
    ) -> ReportLiveTalkResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if report_type is not None:
            params.append([10, 3, report_type])
        return self._call(
            "reportLiveTalk", [[12, 1, params]], response_model=ReportLiveTalkResponse
        )

    def report_live_talk_speaker(
        self,
        square_chat_mid: Optional[str] = None,
        session_id: Optional[str] = None,
        speaker_member_mid: Optional[str] = None,
        report_type: Optional["LiveTalkReportType"] = None,
    ) -> ReportLiveTalkSpeakerResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        if speaker_member_mid is not None:
            params.append([11, 3, speaker_member_mid])
        if report_type is not None:
            params.append([10, 4, report_type])
        return self._call(
            "reportLiveTalkSpeaker",
            [[12, 1, params]],
            response_model=ReportLiveTalkSpeakerResponse,
        )

    def report_message_summary(
        self,
        chat_emid: Optional[str] = None,
        message_summary_range_to: Optional[int] = None,
        report_type: Optional["MessageSummaryReportType"] = None,
    ) -> ReportMessageSummaryResponse:
        params = []
        if chat_emid is not None:
            params.append([11, 1, chat_emid])
        if message_summary_range_to is not None:
            params.append([10, 2, message_summary_range_to])
        if report_type is not None:
            params.append([10, 3, report_type])
        return self._call(
            "reportMessageSummary",
            [[12, 1, params]],
            response_model=ReportMessageSummaryResponse,
        )

    def report_square(
        self,
        square_mid: Optional[str] = None,
        report_type: Optional["ReportType"] = None,
        other_reason: Optional[str] = None,
    ) -> ReportSquareResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        if report_type is not None:
            params.append([10, 3, report_type])
        if other_reason is not None:
            params.append([11, 4, other_reason])
        return self._call(
            "reportSquare", [[12, 1, params]], response_model=ReportSquareResponse
        )

    def report_square_chat(
        self,
        square_mid: Optional[str] = None,
        square_chat_mid: Optional[str] = None,
        report_type: Optional["ReportType"] = None,
        other_reason: Optional[str] = None,
    ) -> ReportSquareChatResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        if square_chat_mid is not None:
            params.append([11, 3, square_chat_mid])
        if report_type is not None:
            params.append([10, 5, report_type])
        if other_reason is not None:
            params.append([11, 6, other_reason])
        return self._call(
            "reportSquareChat",
            [[12, 1, params]],
            response_model=ReportSquareChatResponse,
        )

    def report_square_member(
        self,
        square_member_mid: Optional[str] = None,
        report_type: Optional["ReportType"] = None,
        other_reason: Optional[str] = None,
        square_chat_mid: Optional[str] = None,
        thread_mid: Optional[str] = None,
    ) -> ReportSquareMemberResponse:
        params = []
        if square_member_mid is not None:
            params.append([11, 2, square_member_mid])
        if report_type is not None:
            params.append([10, 3, report_type])
        if other_reason is not None:
            params.append([11, 4, other_reason])
        if square_chat_mid is not None:
            params.append([11, 5, square_chat_mid])
        if thread_mid is not None:
            params.append([11, 6, thread_mid])
        return self._call(
            "reportSquareMember",
            [[12, 1, params]],
            response_model=ReportSquareMemberResponse,
        )

    def report_square_message(
        self,
        square_mid: Optional[str] = None,
        square_chat_mid: Optional[str] = None,
        square_message_id: Optional[str] = None,
        report_type: Optional["ReportType"] = None,
        other_reason: Optional[str] = None,
        thread_mid: Optional[str] = None,
    ) -> ReportSquareMessageResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        if square_chat_mid is not None:
            params.append([11, 3, square_chat_mid])
        if square_message_id is not None:
            params.append([11, 4, square_message_id])
        if report_type is not None:
            params.append([10, 5, report_type])
        if other_reason is not None:
            params.append([11, 6, other_reason])
        if thread_mid is not None:
            params.append([11, 7, thread_mid])
        return self._call(
            "reportSquareMessage",
            [[12, 1, params]],
            response_model=ReportSquareMessageResponse,
        )

    def request_to_listen(
        self, square_chat_mid: Optional[str] = None, session_id: Optional[str] = None
    ) -> RequestToListenResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        return self._call(
            "requestToListen", [[12, 1, params]], response_model=RequestToListenResponse
        )

    def request_to_speak(
        self, square_chat_mid: Optional[str] = None, session_id: Optional[str] = None
    ) -> RequestToSpeakResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if session_id is not None:
            params.append([11, 2, session_id])
        return self._call(
            "requestToSpeak", [[12, 1, params]], response_model=RequestToSpeakResponse
        )

    def search_square_chat_members(
        self,
        square_chat_mid: Optional[str] = None,
        search_option: Optional["SquareChatMemberSearchOption"] = None,
        continuation_token: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> SearchSquareChatMembersResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if search_option is not None:
            params.append([12, 2, search_option])
        if continuation_token is not None:
            params.append([11, 3, continuation_token])
        if limit is not None:
            params.append([8, 4, limit])
        return self._call(
            "searchSquareChatMembers",
            [[12, 1, params]],
            response_model=SearchSquareChatMembersResponse,
        )

    def search_square_chat_mentionables(
        self,
        square_chat_mid: Optional[str] = None,
        search_option: Optional["SquareChatMentionableSearchOption"] = None,
        continuation_token: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> SearchSquareChatMentionablesResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 1, square_chat_mid])
        if search_option is not None:
            params.append([12, 2, search_option])
        if continuation_token is not None:
            params.append([11, 3, continuation_token])
        if limit is not None:
            params.append([8, 4, limit])
        return self._call(
            "searchSquareChatMentionables",
            [[12, 1, params]],
            response_model=SearchSquareChatMentionablesResponse,
        )

    def search_square_members(
        self,
        square_mid: Optional[str] = None,
        search_option: Optional["SquareMemberSearchOption"] = None,
        continuation_token: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> SearchSquareMembersResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        if search_option is not None:
            params.append([12, 3, search_option])
        if continuation_token is not None:
            params.append([11, 4, continuation_token])
        if limit is not None:
            params.append([8, 5, limit])
        return self._call(
            "searchSquareMembers",
            [[12, 1, params]],
            response_model=SearchSquareMembersResponse,
        )

    def search_squares(
        self,
        query: Optional[str] = None,
        continuation_token: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> SearchSquaresResponse:
        params = []
        if query is not None:
            params.append([11, 2, query])
        if continuation_token is not None:
            params.append([11, 3, continuation_token])
        if limit is not None:
            params.append([8, 4, limit])
        return self._call(
            "searchSquares", [[12, 1, params]], response_model=SearchSquaresResponse
        )

    def send_message(
        self,
        req_seq: Optional[int] = None,
        square_chat_mid: Optional[str] = None,
        square_message: Optional["SquareMessage"] = None,
    ) -> SendMessageResponse:
        params = []
        if req_seq is not None:
            params.append([8, 1, req_seq])
        if square_chat_mid is not None:
            params.append([11, 2, square_chat_mid])
        if square_message is not None:
            params.append([12, 3, square_message])
        return self._call(
            "sendMessage", [[12, 1, params]], response_model=SendMessageResponse
        )

    def send_square_thread_message(
        self,
        req_seq: Optional[int] = None,
        chat_mid: Optional[str] = None,
        thread_mid: Optional[str] = None,
        thread_message: Optional["SquareMessage"] = None,
    ) -> SendSquareThreadMessageResponse:
        params = []
        if req_seq is not None:
            params.append([8, 1, req_seq])
        if chat_mid is not None:
            params.append([11, 2, chat_mid])
        if thread_mid is not None:
            params.append([11, 3, thread_mid])
        if thread_message is not None:
            params.append([12, 4, thread_message])
        return self._call(
            "sendSquareThreadMessage",
            [[12, 1, params]],
            response_model=SendSquareThreadMessageResponse,
        )

    def sync_square_members(
        self,
        square_mid: Optional[str] = None,
        square_members: Optional[Dict[str, int]] = None,
    ) -> SyncSquareMembersResponse:
        params = []
        if square_mid is not None:
            params.append([11, 1, square_mid])
        if square_members is not None:
            params.append([13, 2, square_members])
        return self._call(
            "syncSquareMembers",
            [[12, 1, params]],
            response_model=SyncSquareMembersResponse,
        )

    def unhide_square_member_contents(
        self, square_member_mid: Optional[str] = None
    ) -> UnhideSquareMemberContentsResponse:
        params = []
        if square_member_mid is not None:
            params.append([11, 1, square_member_mid])
        return self._call(
            "unhideSquareMemberContents",
            [[12, 1, params]],
            response_model=UnhideSquareMemberContentsResponse,
        )

    def unsend_message(
        self,
        square_chat_mid: Optional[str] = None,
        message_id: Optional[str] = None,
        thread_mid: Optional[str] = None,
    ) -> UnsendMessageResponse:
        params = []
        if square_chat_mid is not None:
            params.append([11, 2, square_chat_mid])
        if message_id is not None:
            params.append([11, 3, message_id])
        if thread_mid is not None:
            params.append([11, 4, thread_mid])
        return self._call(
            "unsendMessage", [[12, 1, params]], response_model=UnsendMessageResponse
        )

    def update_live_talk_attrs(
        self,
        updated_attrs: Optional[List["LiveTalkAttribute"]] = None,
        live_talk: Optional["LiveTalk"] = None,
    ) -> UpdateLiveTalkAttrsResponse:
        params = []
        if updated_attrs is not None:
            params.append([14, 1, updated_attrs])
        if live_talk is not None:
            params.append([12, 2, live_talk])
        return self._call(
            "updateLiveTalkAttrs",
            [[12, 1, params]],
            response_model=UpdateLiveTalkAttrsResponse,
        )

    def update_square(
        self,
        updated_attrs: Optional[List["SquareAttribute"]] = None,
        square: Optional["Square"] = None,
    ) -> UpdateSquareResponse:
        params = []
        if updated_attrs is not None:
            params.append([14, 2, updated_attrs])
        if square is not None:
            params.append([12, 3, square])
        return self._call(
            "updateSquare", [[12, 1, params]], response_model=UpdateSquareResponse
        )

    def update_square_authority(
        self,
        update_attributes: Optional[List["SquareAuthorityAttribute"]] = None,
        authority: Optional["SquareAuthority"] = None,
    ) -> UpdateSquareAuthorityResponse:
        params = []
        if update_attributes is not None:
            params.append([14, 2, update_attributes])
        if authority is not None:
            params.append([12, 3, authority])
        return self._call(
            "updateSquareAuthority",
            [[12, 1, params]],
            response_model=UpdateSquareAuthorityResponse,
        )

    def update_square_chat(
        self,
        updated_attrs: Optional[List["SquareChatAttribute"]] = None,
        square_chat: Optional["SquareChat"] = None,
    ) -> UpdateSquareChatResponse:
        params = []
        if updated_attrs is not None:
            params.append([14, 2, updated_attrs])
        if square_chat is not None:
            params.append([12, 3, square_chat])
        return self._call(
            "updateSquareChat",
            [[12, 1, params]],
            response_model=UpdateSquareChatResponse,
        )

    def update_square_chat_member(
        self,
        updated_attrs: Optional[List["SquareChatMemberAttribute"]] = None,
        chat_member: Optional["SquareChatMember"] = None,
    ) -> UpdateSquareChatMemberResponse:
        params = []
        if updated_attrs is not None:
            params.append([14, 2, updated_attrs])
        if chat_member is not None:
            params.append([12, 3, chat_member])
        return self._call(
            "updateSquareChatMember",
            [[12, 1, params]],
            response_model=UpdateSquareChatMemberResponse,
        )

    def update_square_feature_set(
        self,
        update_attributes: Optional[List["SquareFeatureSetAttribute"]] = None,
        square_feature_set: Optional["SquareFeatureSet"] = None,
    ) -> UpdateSquareFeatureSetResponse:
        params = []
        if update_attributes is not None:
            params.append([14, 2, update_attributes])
        if square_feature_set is not None:
            params.append([12, 3, square_feature_set])
        return self._call(
            "updateSquareFeatureSet",
            [[12, 1, params]],
            response_model=UpdateSquareFeatureSetResponse,
        )

    def update_square_member(
        self,
        updated_attrs: Optional[List["SquareMemberAttribute"]] = None,
        updated_preference_attrs: Optional[List["SquarePreferenceAttribute"]] = None,
        square_member: Optional["SquareMember"] = None,
    ) -> UpdateSquareMemberResponse:
        params = []
        if updated_attrs is not None:
            params.append([14, 2, updated_attrs])
        if updated_preference_attrs is not None:
            params.append([14, 3, updated_preference_attrs])
        if square_member is not None:
            params.append([12, 4, square_member])
        return self._call(
            "updateSquareMember",
            [[12, 1, params]],
            response_model=UpdateSquareMemberResponse,
        )

    def update_square_member_relation(
        self,
        square_mid: Optional[str] = None,
        target_square_member_mid: Optional[str] = None,
        updated_attrs: Optional[List[int]] = None,
        relation: Optional["SquareMemberRelation"] = None,
    ) -> UpdateSquareMemberRelationResponse:
        params = []
        if square_mid is not None:
            params.append([11, 2, square_mid])
        if target_square_member_mid is not None:
            params.append([11, 3, target_square_member_mid])
        if updated_attrs is not None:
            params.append([14, 4, updated_attrs])
        if relation is not None:
            params.append([12, 5, relation])
        return self._call(
            "updateSquareMemberRelation",
            [[12, 1, params]],
            response_model=UpdateSquareMemberRelationResponse,
        )

    def update_square_members(
        self,
        updated_attrs: Optional[List["SquareMemberAttribute"]] = None,
        members: Optional[List["SquareMember"]] = None,
    ) -> UpdateSquareMembersResponse:
        params = []
        if updated_attrs is not None:
            params.append([14, 2, updated_attrs])
        if members is not None:
            params.append([15, 3, members])
        return self._call(
            "updateSquareMembers",
            [[12, 1, params]],
            response_model=UpdateSquareMembersResponse,
        )

    def update_user_settings(
        self,
        updated_attrs: Optional[List[Any]] = None,
        user_settings: Optional["SquareUserSettings"] = None,
    ) -> UpdateUserSettingsResponse:
        params = []
        if updated_attrs is not None:
            params.append([14, 1, updated_attrs])
        if user_settings is not None:
            params.append([12, 2, user_settings])
        return self._call(
            "updateUserSettings",
            [[12, 1, params]],
            response_model=UpdateUserSettingsResponse,
        )
