# -*- coding: utf-8 -*-
# AUTO-GENERATED BY tools/generate_models.py
from typing import List, Optional, Dict, Any
from .services.base import ServiceBase
from .models.sync import *

class SyncService(ServiceBase):
    ENDPOINT = "/SYNC4"
    PROTOCOL = 4

    def sync(self, last_revision: Optional[int] = None, count: Optional[int] = None, last_global_revision: Optional[int] = None, last_individual_revision: Optional[int] = None, full_sync_request_reason: Optional["Pb1_J4"] = None, last_partial_full_syncs: Optional[Dict[int, int]] = None) -> Pb1_X7:
        params = []
        if last_revision is not None:
            params.append([10, 1, last_revision])
        if count is not None:
            params.append([8, 2, count])
        if last_global_revision is not None:
            params.append([10, 3, last_global_revision])
        if last_individual_revision is not None:
            params.append([10, 4, last_individual_revision])
        if full_sync_request_reason is not None:
            params.append([10, 5, full_sync_request_reason])
        if last_partial_full_syncs is not None:
            params.append([13, 6, last_partial_full_syncs])
        return self._call("sync", [[12, 1, params]], response_model=Pb1_X7)
